spring.application.name=tactimind-backend
server.port=8080

tactimind.match.events-file=../data/match_events.json
tactimind.match.tick-millis=2000
tactimind.match.recent-window-size=6

tactimind.agent.base-url=http://127.0.0.1:8000

tactimind.redis.enabled=true
tactimind.redis.ttl-seconds=7200
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.timeout=1000ms

tactimind.mysql.enabled=true
tactimind.mysql.url=jdbc:mysql://127.0.0.1:3306/tactimind?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
tactimind.mysql.username=root
tactimind.mysql.password=1234

spring.jackson.serialization.indent-output=true
